Citizen.CreateThread(function()
SetDiscordAppId('1140818448813936700')
SetDiscordRichPresenceAsset('pandalogo')
SetDiscordRichPresenceAssetText('Panda Template V1')
SetDiscordRichPresenceAction('PandaTemplate', 0)
SetDiscordRichPresenceAction('fivem://connect/', 1)
Citizen.Wait(0)
print("test")
end)